main:
	gcc -o preflow preflow.c -g -O3 -pthread
	time sh check-solution.sh ./preflow
	@echo PASS all tests

#	time sh check-solution.sh ./preflow		// for all
#	@echo PASS all tests

#	./preflow < ../../data/tiny/0.in		// for one
